version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Uevent
      TZ: Europe/Kyiv
      PGTZ: Europe/Kyiv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: Uevent
      TZ: Europe/Kyiv
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
